name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build app
        run: ./mvnw package

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/SAJAT_USER/cubix:latest .

      - name: Push image
        run: docker push ghcr.io/SAJAT_USER/cubix:latest

  verify:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify image
        run: chmod +x verify-image.sh && ./verify-image.sh